### ISSUE TITLE
API to get backtrace details for use with Rollbar, etc.?

### ISSUE THREAD

**Issue by emk** [rust-lang-nursery/failure#206] opened 2018-05-16 12:50 UTC
I've been porting a bunch of code at work from `error-chain` to `backtrace`, and I'm really happy with the results!

But I've run into a problem: The `failure::Backtrace` type is opaque. We use [Rollbar](https://rollbar.com/) to monitor errors in all our servers, and [Rollbar requires stack frame details to correctly log errors](https://docs.rs/rollbar/0.5.0/rollbar/struct.FrameBuilder.html). If the frame information is omitted, Rollbar can't identify duplicate errors correctly.

Would it be possible to export a basic API for walking the stack frames in the backtrace, so that they can be reported to Rollbar or another external error reporting system? This doesn't need to expose `backtrace`; it could be an abstract API. I'd be happy to work on implementing it.

The other alternative is to convert backtraces to a string, and then parse them back into a custom data structure.

**Comment by emk** [comment] 2018-05-21 10:40
We would be willing to devote some engineering time to help find a solution for this issue, by the way. :-)

**Comment by withoutboats** [comment] 2018-05-25 23:34
See also the discussion on #133 

Basically, I'm in favor of having a backtrace API, but didn't want to commit to one by myself. I think we should have a larger community wide push around stabilizing a backtrace API, probably first through making the backtrace crate a 1.0 and then through moving it into std.

**Comment by emk** [comment] 2018-05-26 18:06
This seems like a reasonable long-term plan. Thank you!

We'll see if we can cobble together a short-term production solution, perhaps by parsing the textual backtraces.

**Comment by mitsuhiko** [comment] 2018-05-27 19:08
The sentry crate parses the stacktrace with regexes for now. It's not great but it's a reasonable workaround for such cases: https://github.com/getsentry/sentry-rust/blob/master/src/backtrace_support.rs

**Comment by mitsuhiko** [comment] 2018-07-27 18:22
Duplicate of #161

**Closed by mitsuhiko** 2018-07-27 18:22 UTC
Labels: feature-request
