### ISSUE TITLE
Fail::context destroys the existing error instead of enriching it with context

### ISSUE THREAD

**Issue by marmistrz** [rust-lang-nursery/failure#219] opened 2018-06-14 14:35 UTC
```
extern crate failure;
use failure::ResultExt;
use std::fs::File;

type FailResult<T> = Result<T, failure::Error>;

fn opensome() -> FailResult<()> {
    File::open("/nonexisintg")?;
    Ok(())
}

fn try_open() -> FailResult<()> {
    println!("Trying");
    opensome().context("failed while trying")?;
    Ok(())
}

fn run() -> FailResult<()> {
    try_open()
}

fn main() {
    if let Err(e) = run() {
        eprintln!("error: {}", e);
        std::process::exit(1);
    }
}
```
Actual output 
```
Trying
error: run function
```
Expected output
```
Trying
error: run function, failed while trying, No such file or directory (os error 2)
```
(or something similar, at the very least - not destroying the existing context.

---------------------

Moreover: `e.backtrace()` is empty, `e.cause()` is `run function`. This certainly shouldn't look like that.

**Comment by mbrubeck** [comment] 2018-06-22 18:22
You can call `cause` in a loop to walk up the stack of wrapped errors.  This code:

```rust
    if let Err(e) = run() {
        eprint!("error: {}", e);
        let mut cause = e.cause();
        loop {
            eprint!(", {}", cause);
            cause = match cause.cause() {
                Some(e) => e,
                None => break,
            };
        }
        eprintln!("");
        std::process::exit(1);
    }
```

prints:

```text
Trying
error: failed while trying, failed while trying, No such file or directory (os error 2)
```

**Comment by mitsuhiko** [comment] 2018-07-28 08:40
I'm going to close this since we provide access to the causes. However it did come up before and i think it makes sense to provide a default helper printer for this that also involves causes.

**Closed by mitsuhiko** 2018-07-28 08:40 UTC

**Comment by marmistrz** [comment] 2018-08-28 19:39
@mitsuhiko do you mean `iter_causes`, as modified in here?

**Comment by mitsuhiko** [comment] 2018-08-28 19:53
@marmistrz `iter_causes` and `iter_chain`.
